### ISSUE TITLE
Extra line after table

### ISSUE THREAD

**Issue by inzhir** [dothinking/pdf2docx#76] opened 2021-04-20 12:18 UTC
Hi Team
Have problem with parsing my pdf report 
An extra line is always added after each table. Is there any way I can fix it?

Thank you!

Original pdf and result docx :
[myreport.pdf](https://github.com/dothinking/pdf2docx/files/6343371/myreport.pdf)
[myreport.docx](https://github.com/dothinking/pdf2docx/files/6343376/myreport.docx)

**Comment by dothinking** [comment] 2021-04-21 14:45
Many thanks to report this issue. 

The root cause is a fact in Word document that **an empty line is always created automatically when insert a nested table into a cell**. So, a fix is to delete such line -> will be included in next version.

For now, you can modify the source code based on version `0.5.1`:

1. Find `Blocks.py`

```python
>>> import pdf2docx
>>> pdf2docx.page.Blocks.__file__
'd:\\workspace\\github\\pdf2docx\\pdf2docx\\page\\Blocks.py'
```

2. Check lines 523-538 of method `make_docx()`

```python
for block in self._instances:
    # make paragraphs
    if block.is_text_image_block():
        # new paragraph
        p = doc.add_paragraph()
        block.make_docx(p)

        pre_table = False # mark block type
    
    # make table
    elif block.is_table_block():
        make_table(block, pre_table)
        pre_table = True # mark block type

# below table processing is necessary for page level only
if isinstance(self.parent, Cell): return
```

3. Change to as follows

```python
for block in self._instances:
    # make paragraphs
    if block.is_text_image_block():                
        # new paragraph
        p = doc.add_paragraph()
        block.make_docx(p)

        pre_table = False # mark block type
    
    # make table
    elif block.is_table_block():
        make_table(block, pre_table)
        pre_table = True # mark block type

        # NOTE: within a cell, there is always an empty paragraph after table,
        # so, delete it right here
        if isinstance(self.parent, Cell):
            delete_paragraph(doc.paragraphs[-1])
```

Note to import method `delete_paragraph()` accordingly:

```python
from ..common.docx import reset_paragraph_format, delete_paragraph
```

**Comment by inzhir** [comment] 2021-04-21 15:50
Thank you for your fast reply!

Fixed code this way
```python
if isinstance(self.parent._parent, Cell):
    delete_paragraph(doc.paragraphs[-1])
```
(added **_parent**) and now everything works.

**Comment by dothinking** [comment] 2021-04-21 17:27
Ah, my fix was based on `dev`. Per version `0.5.1`, `self.parent` -> `Layout`, then `Layout._parent` -> `Cell`.

So, thank you for figuring it out

**Closed** 2021-04-22 02:58 UTC
Labels: bug
