### ISSUE TITLE
Rotate the image 90°

### ISSUE THREAD

**Issue by oldlwhite** [dothinking/pdf2docx#125] opened 2022-01-12 06:13 UTC
This is the source file
[test.pdf](https://github.com/dothinking/pdf2docx/files/7852137/test.pdf)

**Comment by dothinking** [comment] 2022-02-11 17:58
Thanks for providing the test document. 

Same issue with #110, the root cause is page rotation. It was fixed and plans to be released in the coming v0.5.3.

**Comment by dothinking** [comment] 2022-02-21 04:20
close issue for now since `v0.5.3` is released.

**Closed by dothinking** 2022-02-21 04:20 UTC
Labels: bug
